spring:
  profiles:
    default: prod

---
spring:
  config:
    activate:
      on-profile: prod

management:
  endpoint:
    health:
      enabled: true
    beans:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - loggers
          - quartz
          - caches
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
